-- TTD pemohon jadi dua lapis: digital di dashboard, lalu basah di atas kertas.
--
-- Alur baru pada status 'Menunggu TTD':
--   1. Pemohon membubuhkan tanda tangan digital ke dokumen resmi (signature pad).
--   2. Pemohon mencetak dokumen itu dan meminta tanda tangan basah atasan
--      langsung pada kolom "Mengetahui".
--   3. Pemohon memindai/memotret dokumen tersebut dan mengunggahnya kembali.
--      Scan itu disimpan sebagai kind 'ttd_pemohon'.
--   4. Barulah pengajuan boleh pindah ke 'Menunggu Review'.
--
-- Tahap 'Menunggu TTD Basah' (admin mengedarkan cetakan ke wakil ketua, ketua,
-- sekretaris, bendahara lalu mengunggah 'ttd_scan') tidak berubah — ia tetap
-- gerbang terakhir sebelum pencairan.

-- ---------------------------------------------------------------------------
-- Jenis dokumen baru
-- ---------------------------------------------------------------------------

ALTER TABLE public.documents DROP CONSTRAINT documents_kind_check;
ALTER TABLE public.documents ADD CONSTRAINT documents_kind_check
  CHECK (kind IN (
    'permohonan',   -- Lembar Permohonan (generated by admin)
    'persetujuan',  -- Lembar Persetujuan (generated by admin)
    'penyerahan',   -- Lembar Penyerahan (generated by admin)
    'ttd_pemohon',  -- scan TTD pemohon + atasan langsung, diunggah pemohon
    'ttd_scan',     -- scan dokumen lengkap (TTD manajemen), diunggah admin
    'ttd_digital'   -- hasil signature pad (legacy)
  ));

-- ---------------------------------------------------------------------------
-- Siapa boleh melampirkan dokumen apa
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.guard_document_insert()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_uid        UUID    := auth.uid();
  v_is_service BOOLEAN := v_uid IS NULL;
  v_owner      UUID;
  v_status     TEXT;
BEGIN
  SELECT a.user_id, a.status INTO v_owner, v_status
  FROM public.applications a WHERE a.id = NEW.application_id;

  IF v_owner IS NULL THEN
    RAISE EXCEPTION 'application % not found', NEW.application_id;
  END IF;

  NEW.user_id     := v_owner;
  NEW.uploaded_by := v_uid;

  IF v_is_service OR public.is_admin() THEN
    RETURN NEW;
  END IF;

  IF v_owner IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'not allowed to attach documents to this application';
  END IF;

  -- 'ttd_scan' tetap milik admin: dokumen itulah yang membuka gerbang
  -- pencairan, jadi pemohon tidak boleh membuatnya sendiri.
  IF NEW.kind <> 'ttd_pemohon' THEN
    RAISE EXCEPTION
      'pemohon hanya boleh mengunggah scan dokumen bertanda tangan pemohon dan atasan langsung';
  END IF;

  IF v_status <> 'Menunggu TTD' THEN
    RAISE EXCEPTION
      'scan hanya bisa diunggah saat pengajuan berstatus "Menunggu TTD"';
  END IF;

  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Guard transisi: 'Menunggu Review' hanya jika scan pemohon sudah masuk
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.applications_guard_update()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_uid          UUID    := auth.uid();
  v_is_service   BOOLEAN := v_uid IS NULL;
  v_is_admin     BOOLEAN := public.is_admin();
  v_is_owner     BOOLEAN := COALESCE(OLD.user_id = v_uid, FALSE);
  v_is_system    BOOLEAN := pg_trigger_depth() > 1
    AND OLD.status IN ('Disetujui / Cair', 'Lunas')
    AND NEW.status IN ('Disetujui / Cair', 'Lunas');
  v_has_scan     BOOLEAN;
  v_has_own_scan BOOLEAN;
BEGIN
  IF v_is_system OR v_is_service THEN
    RETURN NEW;
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.code IS DISTINCT FROM OLD.code
     OR NEW.user_id IS DISTINCT FROM OLD.user_id
     OR NEW.submitted_at IS DISTINCT FROM OLD.submitted_at
     OR NEW.remaining_contract_days IS DISTINCT FROM OLD.remaining_contract_days
  THEN
    RAISE EXCEPTION 'code, user_id and submission snapshot fields are immutable';
  END IF;

  IF NOT v_is_admin THEN
    IF NOT v_is_owner THEN
      RAISE EXCEPTION 'not allowed to modify this application';
    END IF;

    IF NEW.status = OLD.status THEN
      IF OLD.status <> 'Diajukan' THEN
        RAISE EXCEPTION 'application can only be edited while status is "Diajukan"';
      END IF;
    ELSIF OLD.status = 'Menunggu TTD' AND NEW.status = 'Menunggu Review' THEN
      -- Scan harus lebih baru dari saat dokumen dikirim, supaya pengajuan yang
      -- dikembalikan admin tidak lolos memakai scan lama.
      SELECT EXISTS (
        SELECT 1 FROM public.documents d
        WHERE d.application_id = NEW.id
          AND d.kind = 'ttd_pemohon'
          AND d.created_at >= COALESCE(OLD.document_sent_at, OLD.submitted_at)
      ) INTO v_has_own_scan;

      IF NOT v_has_own_scan THEN
        RAISE EXCEPTION
          'scan dokumen bertanda tangan pemohon dan atasan langsung harus diunggah dulu';
      END IF;

      NEW.signed_at := NOW();
    ELSE
      RAISE EXCEPTION 'transition % -> % is not allowed for an applicant',
        OLD.status, NEW.status;
    END IF;

    IF NEW.admin_note IS DISTINCT FROM OLD.admin_note
       OR NEW.reviewed_by IS DISTINCT FROM OLD.reviewed_by
       OR NEW.reviewed_at IS DISTINCT FROM OLD.reviewed_at
       OR NEW.disbursed_at IS DISTINCT FROM OLD.disbursed_at
    THEN
      RAISE EXCEPTION 'review fields are admin-only';
    END IF;

    RETURN NEW;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NOT (
         (OLD.status = 'Diajukan'           AND NEW.status IN ('Diproses Admin', 'Ditolak'))
      OR (OLD.status = 'Diproses Admin'     AND NEW.status IN ('Menunggu TTD', 'Ditolak'))
      OR (OLD.status = 'Menunggu TTD'       AND NEW.status IN ('Menunggu Review', 'Ditolak'))
      OR (OLD.status = 'Menunggu Review'    AND NEW.status IN ('Menunggu TTD Basah', 'Ditolak', 'Menunggu TTD'))
      OR (OLD.status = 'Menunggu TTD Basah' AND NEW.status IN ('Disetujui / Cair', 'Ditolak', 'Menunggu Review'))
      OR (OLD.status = 'Ditolak'            AND NEW.status IN ('Diproses Admin', 'Menunggu TTD'))
    ) THEN
      RAISE EXCEPTION 'transition % -> % is not allowed', OLD.status, NEW.status;
    END IF;

    -- Uang hanya keluar kalau dokumen bertanda tangan lengkap sudah diarsipkan.
    IF NEW.status = 'Disetujui / Cair' THEN
      SELECT EXISTS (
        SELECT 1 FROM public.documents d
        WHERE d.application_id = NEW.id AND d.kind = 'ttd_scan'
      ) INTO v_has_scan;

      IF NOT v_has_scan THEN
        RAISE EXCEPTION
          'scan dokumen bertanda tangan lengkap harus diunggah sebelum pencairan';
      END IF;
    END IF;

    IF NEW.status = 'Diproses Admin' AND NEW.processed_at IS NULL THEN
      NEW.processed_at := NOW();
    END IF;
    IF NEW.status = 'Menunggu TTD' THEN
      NEW.document_sent_at := NOW();
    END IF;
    IF NEW.status = 'Menunggu TTD Basah' THEN
      NEW.wet_signature_at := NOW();
    END IF;
    IF NEW.status IN ('Disetujui / Cair', 'Ditolak') THEN
      NEW.reviewed_by := v_uid;
      NEW.reviewed_at := NOW();
    END IF;
    IF NEW.status = 'Disetujui / Cair' AND NEW.disbursed_at IS NULL THEN
      NEW.disbursed_at := NOW();
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Isi notifikasi mengikuti langkah baru
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.notify_application_change()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_admin      RECORD;
  v_name       TEXT;
  v_amount     TEXT;
BEGIN
  SELECT COALESCE(NULLIF(p.full_name, ''), p.email) INTO v_name
  FROM public.profiles p WHERE p.id = NEW.user_id;
  v_name   := COALESCE(v_name, 'Pemohon');
  v_amount := 'Rp ' || to_char(NEW.amount, 'FM999G999G999G999');

  IF TG_OP = 'INSERT' THEN
    FOR v_admin IN SELECT id FROM public.profiles WHERE role = 'admin' LOOP
      PERFORM public.enqueue_notification(
        v_admin.id, 'pengajuan_baru',
        'Pengajuan kasbon baru: ' || NEW.code,
        v_name || ' mengajukan kasbon ' || v_amount || ' (' || NEW.reason_category || ').',
        NEW.id
      );
    END LOOP;
    RETURN NEW;
  END IF;

  IF NEW.status IS NOT DISTINCT FROM OLD.status THEN
    RETURN NEW;
  END IF;

  CASE NEW.status
    WHEN 'Menunggu TTD' THEN
      PERFORM public.enqueue_notification(
        NEW.user_id, 'dokumen_siap_ttd',
        'Dokumen kasbon ' || NEW.code || ' siap ditandatangani',
        'Dokumen permohonan kasbon kamu sudah disiapkan admin. Buka dashboard '
          || 'Kasbonku untuk membubuhkan tanda tangan, lalu cetak dokumennya, '
          || 'minta tanda tangan basah atasan langsung, dan unggah kembali hasil '
          || 'scan-nya.',
        NEW.id
      );

    WHEN 'Menunggu Review' THEN
      FOR v_admin IN SELECT id FROM public.profiles WHERE role = 'admin' LOOP
        PERFORM public.enqueue_notification(
          v_admin.id, 'ttd_diterima',
          'Dokumen TTD diterima: ' || NEW.code,
          v_name || ' sudah mengunggah scan dokumen bertanda tangan pemohon dan '
            || 'atasan langsung. Menunggu review admin.',
          NEW.id
        );
      END LOOP;

    WHEN 'Menunggu TTD Basah' THEN
      PERFORM public.enqueue_notification(
        NEW.user_id, 'ttd_basah_proses',
        'Kasbon ' || NEW.code || ' sedang dikumpulkan tanda tangannya',
        'Dokumen kamu sudah lolos review admin dan sekarang dicetak untuk tanda '
          || 'tangan wakil ketua, ketua, sekretaris, dan bendahara. Kamu akan '
          || 'diberi kabar lagi setelah dokumen lengkap dan dana siap dicairkan.',
        NEW.id
      );

    WHEN 'Disetujui / Cair' THEN
      PERFORM public.enqueue_notification(
        NEW.user_id, 'review_disetujui',
        'Kasbon ' || NEW.code || ' disetujui',
        'Pengajuan kasbon ' || v_amount || ' sudah disetujui dan dana dicairkan. '
          || 'Angsuran akan dipotong dari gaji selama ' || NEW.tenure_months || ' bulan.',
        NEW.id
      );

    WHEN 'Ditolak' THEN
      PERFORM public.enqueue_notification(
        NEW.user_id, 'review_ditolak',
        'Kasbon ' || NEW.code || ' perlu revisi',
        COALESCE(
          NULLIF(NEW.admin_note, ''),
          'Pengajuan kamu ditolak. Silakan revisi data dan ajukan ulang.'
        ),
        NEW.id
      );

    WHEN 'Lunas' THEN
      PERFORM public.enqueue_notification(
        NEW.user_id, 'kasbon_lunas',
        'Kasbon ' || NEW.code || ' lunas',
        'Seluruh angsuran kasbon ' || v_amount || ' sudah selesai dipotong. Terima kasih.',
        NEW.id
      );

    ELSE
      NULL;
  END CASE;

  RETURN NEW;
END;
$$;
